Repository mash-up-kr/HikingClub_Web, pull requests merged in 2021-11, with the labels that each got.

#19 Features/detail page enhance
  public/images/remove-hashtag.png
  src/components/atoms/BasicButton.tsx
  src/components/atoms/Button.tsx
  src/components/modules/RoadContent.tsx
  src/components/modules/RoadHashTag.tsx
  src/components/modules/RoadSubmit.tsx
  src/components/modules/RoadTag.tsx
  src/components/modules/RoadTitle.tsx
  src/components/templates/Category.tsx
  src/components/templates/MakeRoad.tsx
  src/models/Road.ts
  src/stores/ActionTypes.ts
  src/stores/actions/editActions.ts
  src/stores/reducers/editReducer.ts
  src/stores/reducers/index.ts
  src/stores/selectors/editSelectors.ts
Labels: feature

#22 길그리기 로직 구현
  public/images/revert.png
  public/images/search-icon.png
  public/images/trash.png
  src/components/atoms/Input.tsx
  src/components/atoms/Map.tsx
  src/components/modules/Header.tsx
  src/components/modules/Overlay/Overlay.tsx
  src/components/modules/RoadCategory.tsx
  src/components/modules/RoadContent.tsx
  src/components/modules/RoadHashTag.tsx
  src/components/modules/RoadImageUploader.tsx
  src/components/modules/RoadMap.tsx
  src/components/modules/RoadTitle.tsx
  src/components/templates/DrawRoad.tsx
  src/components/templates/MakeRoad.tsx
  src/hooks/useMounted.tsx
  src/services/KakaoMapService.ts
  src/stores/ActionTypes.ts
  src/stores/actions/editActions.ts
  src/stores/reducers/editReducer.ts
  src/stores/selectors/editSelectors.ts
  src/styles/globals.css
  src/utils/domUtils.ts
Labels: feature

#21 BottomSheet 확대 축소 기능 및 리액션 컴포넌트 추가
  public/images/icon_emoji_disappointed_16.png
  public/images/icon_emoji_heartEyes_16.png
  public/images/icon_emoji_surprised_16.png
  public/images/icon_emoji_thumbsUp_16.png
  public/images/stroke.png
  src/components/atoms/ReactionChip.tsx
  src/components/modules/ReactionBox.tsx
  src/components/templates/BottomSheet.tsx
  src/pages/detail/[id].tsx
Labels: enhancement

#23 라우팅 에러 수정
  public/images/menu.png
  src/pages/detail.tsx
  src/pages/edit.tsx
  src/utils/urlUtils.ts
Labels: bug

#25 Featuees/spot rebuild
  src/components/modules/RoadMap.tsx
  src/components/templates/Category.tsx
  src/components/templates/DrawRoad.tsx
  src/components/templates/MakeRoad.tsx
  src/pages/detail.tsx
  src/pages/edit.tsx
Labels: feature

#27 임시로 인증 토큰 추가
  public/images/spot-remove.png
  public/images/spot.png
  src/stores/apis/roadAPI.ts
Labels: feature

#31 Features/edit spot build
  src/components/modules/RoadMap.tsx
  src/components/modules/RoadSubmit.tsx
  src/components/templates/Category.tsx
  src/components/templates/DrawRoad.tsx
  src/components/templates/MakeRoad.tsx
  src/constants/category.ts
  src/models/Route.ts
  src/models/Spot.ts
  src/pages/detail.tsx
  src/services/KakaoMapService.ts
  src/stores/ActionTypes.ts
  src/stores/actions/editActions.ts
  src/stores/apis/editAPI.ts
  src/stores/epics/editEpic.ts
  src/stores/epics/index.ts
  src/stores/reducers/editReducer.ts
  src/stores/selectors/editSelectors.ts
Labels: feature

#32 상세페이지 지도 동기화
  src/components/templates/MakeRoad.tsx
  src/pages/detail.tsx
Labels: feature

#34 mock데이터 다양화
  src/stores/reducers/editReducer.ts
Labels: enhancement

#36 kakao에러 수정
  src/services/KakaoMapService.ts
Labels: bug

#37 카카오 에러 수정
  src/services/KakaoMapService.ts
Labels: bug

#38 신고하기 클릭스 알럿뜨게 추가
  src/pages/detail.tsx
Labels: feature

#40 spot 내용 입력할수 있도록 구현
  src/components/templates/DrawRoad.tsx
  src/stores/ActionTypes.ts
  src/stores/actions/editActions.ts
  src/stores/reducers/editReducer.ts
Labels: feature

#26 길 공유, 삭제 기능 추가
  src/pages/detail.tsx
  src/stores/ActionTypes.ts
  src/stores/actions/roadActions.ts
  src/stores/apis/roadAPI.ts
  src/stores/epics/roadEpic.ts
  src/stores/reducers/roadReducer.ts
  src/stores/selectors/roadSelectors.ts
Labels: enhancement

#41 지도오류 수정
  src/components/modules/RoadMap.tsx
  src/components/templates/DrawRoad.tsx
  src/constants/requestTimeout.ts
  src/pages/detail.tsx
  src/services/KakaoMapService.ts
  src/stores/apis/roadAPI.ts
Labels: bug

#43 상세페이지에서 뒤로가기 기능추가 / 리액션, 북마크 임시제거 / 길 저장, 수정 실패시 에러메세지 뜨도록 변경
  public/images/detail-back.png
  src/components/modules/StreetInfo.tsx
  src/components/templates/MakeRoad.tsx
  src/pages/detail.tsx
  src/stores/actions/editActions.ts
  src/stores/apis/editAPI.ts
  src/stores/epics/editEpic.ts
  src/stores/epics/roadEpic.ts
  src/stores/reducers/editReducer.ts
  src/stores/selectors/editSelectors.ts
Labels: feature
