Repository mash-up-kr/HikingClub_Web, pull requests merged in 2021-10, with the labels that each got.

#3 feat: lint, prettier 적용
  .eslintignore
  .eslintrc
  .eslintrc.json
  .husky/pre-commit
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  lint-staged.config.js
  next.config.js
  package.json
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  tsconfig.json
  yarn.lock
Labels: feature

#4 Layout컴포넌트 구현
  .eslintrc
  src/components/Layout.tsx
  src/components/atoms/.gitkeep
  src/components/modules/.gitkeep
  src/pages/_document.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: feature

#2 feat: 길 상세 페이지 컴포넌트를 만든다.
  .eslintrc
  src/assets/images/leaf.svg
  src/assets/images/location.svg
  src/assets/images/specialSpot.svg
  src/components/atoms/CategoryText.tsx
  src/components/atoms/Chip.tsx
  src/components/atoms/LocationText.tsx
  src/components/modules/ImageDetail.tsx
  src/components/modules/Spot.tsx
Labels: enhancement

#6 map 서비스 구현
  package.json
  src/components/atoms/Map.tsx
  src/pages/detail/[id].tsx
  src/pages/edit.tsx
  src/pages/register.tsx
  src/services/KakaoMapService.ts
  yarn.lock
Labels: feature

#8 AWS S3 배포 스크립트 추가합니다.
  .github/workflows/react-build-deploy.yml
Labels: enhancement

#9 배포를 위해 임시로 import order린트 off
  .eslintrc
  src/components/atoms/CategoryText.tsx
Labels: bug

#11 길등록 페이지 작성
  src/components/atoms/.gitkeep
  src/components/atoms/Input.tsx
  src/components/atoms/Spot.tsx
  src/components/atoms/TextArea.tsx
  src/components/modules/.gitkeep
  src/components/modules/Header.tsx
  src/components/modules/ImageList.tsx
  src/components/modules/LoadMap.tsx
  src/components/modules/LoadTag.tsx
  src/components/modules/LoadTitle.tsx
  src/components/templates/BottomSheet.tsx
  src/components/templates/MakeLoad.tsx
  src/pages/detail/[id].tsx
  src/pages/edit.tsx
  src/pages/register.tsx
  src/styles/globals.css
Labels: feature
